# web_scrapper:
# 	python3 create_player_urls.py
# 	python3 create_dst_rankings.py
# 	python3 create_weekly_data.py
# 	python3 create_skill_scores.py
# 	python3 create_rookie_seasons.py
# 	python3 create_data.py

# data.txt:
# 	python3 create_weekly_data.py
# 	python3 create_skill_scores.py
# 	python3 create_rookie_seasons.py
# 	python3 create_data.py

clean:
	rm *.out *.txt