create_data_tests:
	python3 -m web_scrapper.skill_scores.create_skill_scores_tests
	python3 -m web_scrapper.weekly_data.create_weekly_data_tests
	python3 -m web_scrapper.rookie_seasons.create_rookie_seasons_tests
	python3 -m web_scrapper.team_id.create_team_id_tests
	python3 -m web_scrapper.data.create_data_tests
  
data.csv:
	python3 -m web_scrapper.skill_scores.create_skill_scores
	python3 -m web_scrapper.weekly_data.create_weekly_data
	python3 -m web_scrapper.rookie_seasons.create_rookie_seasons
	python3 -m web_scrapper.team_id.create_team_id
	python3 -m web_scrapper.data.create_data

.PHONY: 

clean:
	 